In [54]:
import matplotlib.pyplot as plt
from functools import partial, reduce 
import numpy as np
import math

In [5]:
# 벡터 list 로 간단하게 표현
height_weight_age = [70,170, 40]  # 인치, 파운드, 나이
grades = [95,
                 80,
             75,
             62]

def vector_add(v,w):
    '''각 성분끼리 더함'''
    return [v_i +w_i
           for v_i,w_i in zip(v,w)
           ]



In [13]:
v = [x for x in range(1, 11,2)]
w = [y for y in range(11, 21,2)]
print("v : ",v)
print("w :",w )

v :  [1, 3, 5, 7, 9]
w : [11, 13, 15, 17, 19]


In [7]:
vector_add(v,w)

[12, 16, 20, 24, 28]

In [17]:
#numpy version
np.array(v)+np.array(w)


array([12, 16, 20, 24, 28])

In [18]:
def vector_subtract(v,w):
    '''각 성분끼리 뺌'''
    return [v_i - w_i
           for v_i, w_i in zip(v,w)]



In [19]:
vector_subtract(v,w)

[-10, -10, -10, -10, -10]

In [20]:
np.array(v) - np.array(w)

array([-10, -10, -10, -10, -10])

In [29]:
'''
def vector_sum(vectors):
    #모든 벡터의 각 성분들끼리 더함
    result = vectors[0]     #첫 번째 벡터부터 시작해서
    for vector in vectors[1: ]:   #나머지 벡터들을
        result = vector_add(result,vector)
    return result
'''

def vector_sum(vectors):
    return reduce(vector_add, vectors)


vectors=[v,w,v,w,v,w]
vector_sum(vectors)



[36, 48, 60, 72, 84]

__scalar vector 연산 =>  3*[1,2,3,4] = [3,6,9,12]

In [36]:
def scalar_multiply(c,v):
    # c는 숫자, v는 벡터
    return [c * v_i for v_i in v]

v= [1,2,3,4]
scalar = 3
scalar_multiply(scalar,v)

[3, 6, 9, 12]

In [37]:
scalar * np.array(v)

array([ 3,  6,  9, 12])

__vector 평균 구하기__



In [38]:
def vector_mean(vectors):
    # i번째 성분이 입력된 벡터의 i번째 성분의 평균 의미하는 벡터 계산해줌
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

In [42]:
v= [1,2,3,4]
w = [-4,-3,-2,-1]

vector_mean([v,v,v,v,v])

[1.0, 2.0, 3.0, 4.0]

In [44]:
np.mean([v,v,v,v,v], axis=0)

array([1., 2., 3., 4.])

In [45]:
def dot(v,w):
    # v_1 * w_i + ... v_n * w_n
    return sum(v_i * w_i for v_i,w_i in zip(v,w))

In [ ]:
v= [1,3,5,7]
w = [2,4,6,8]
# 1*2 + 3*4 + 5*6 + 7*8 =100
dot(v,w)

In [49]:
# Numpy version
np.dot(v,w)

100

In [52]:
def sum_of_squares(v):
    # v_i * v_i + ... v_n * v_n
    return dot(v,v)

v=[1,3]
# 1*1 +3*3 = 10
sum_of_squares(v)

10

In [53]:
# Numpy version
np.dot(v,v) # or sum(np.square(v))

10

__magnitude :  하나의 벡터를 dot_product(내적) 한후 양의 제곱근 구함

In [57]:
def magnitude(v):
    return math.sqrt(sum_of_squares(v))  # math.sqrt는 제곱근을 계산해주는 함수

In [58]:
magnitude(v)

3.1622776601683795

In [59]:

# Numpy version
#Norm은 벡터의 길이 혹은 크기를 측정하는 방법(함수)입니다. Norm이 측정한 벡터의 크기는 원점에서 벡터 좌표까지의 거리 혹은 Magnitude라고 

np.linalg.norm(v)

3.1622776601683795

__두 벡터간의 거리 계산


In [61]:
def squared_distance(v,w):
    #(v_i - w_i) **2 + ...+(v_n - w_n)**2
    return sum_of_squares(vector_subtract(v,w))

'''
def distance(v,w):
    return math.sqrt(squared_distance(v,w))
    '''
def distance(v,w):
    return magnitude(vector_subtract(v,w))

In [62]:
v = [1,2,3,4]
w = [-4,-3,-2,-1]

squared_distance(v,w)

100

In [63]:
distance(v,w)

10.0

In [64]:
# Numpy version
np.linalg.norm(np.subtract(v,w)) # or np.sqrt(np.sum(np.subtract(v,w)**2))

10.0

__Matrix__
 - shape : matrix 크기
 - get_row : matrix에서 하나의 row 추출
 - get_column : matrix 에서 하나의 column 추출

In [66]:
def shape(A):
    num_rows=len(A)
    num_cols=len(A[0])
    return num_rows, num_cols

def get_row(A,i):
    return A[i]

def get_column(A,j):
    return [A_i[j] for A_i in A ]

In [67]:
example_matrix = [[1,2,3,4,5], 
                              [11,12,13,14,15], 
                              [21,22,23,24,25] ]

shape(example_matrix)

(3, 5)

In [68]:
get_row(example_matrix,2)

[21, 22, 23, 24, 25]

In [69]:
get_column(example_matrix,1)

[2, 12, 22]

In [70]:
# Numpy version 
np.shape(example_matrix)

(3, 5)

In [71]:
example_matrix = np.array(example_matrix)
example_matrix[0] #row slicing

array([1, 2, 3, 4, 5])

In [72]:
example_matrix[:,3] #row slicing

array([ 4, 14, 24])

__Matrix operation__


In [75]:
def make_matrix(num_rows,num_cols,entry_fn):
    #(i, j) 번째 원소가 entry_fn(i,j) 인 num_rows x num_cols list반환
    return [[entry_fn(i,j) 
            for j in range(num_cols)]
           for i in range(num_rows) ]
    

In [79]:
def is_diagonal(i,j):
    # 대각선의 원소는 1 나머지 원소는 0
    return 1  if i ==j else 0 

In [81]:
identity_matrix = make_matrix(5,5, is_diagonal)

identity_matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [82]:
# Numpy version
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])